const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const path=require('node:path'),root=path.join(__dirname,'..');
const elements=new Map();
function element(){return {innerHTML:'',textContent:'',style:{},dataset:{},children:[],prepend(e){this.children.unshift(e)},append(e){this.children.push(e)},querySelector(c){return this.children.find(e=>'.'+e.className===c)||null}};}
function node(id){if(!elements.has(id))elements.set(id,element());return elements.get(id);}
const memory=new Map();let blocked=false;
const storage={getItem:k=>memory.get(k)||null,setItem(k,v){if(blocked)throw Error('quota');memory.set(k,v)}};
const ctx={console,Date,Map,Set,Number,String,Promise,localStorage:storage,document:{hidden:false,createElement:element,getElementById:node,querySelector:node,addEventListener(){}},setInterval(){},addEventListener(){},esc:String,requireMembership:()=>true,normTeam:String,nflOpponentFor:()=>null,j:async()=>({}),state:{memberActive:true,games:[],currentLab:{id:1,name:'Batter',team:'A'},nfl:{players:[{id:'1',name:'QB',team:'B'}]},nflCurrentPlayer:'1',weather:new Map()},renderBatterAnalytics(){},renderPitcherAnalytics(){},openNFLPlayer(){},ymd:'2026-09-10',MLB:'mock'};
ctx.window=ctx;vm.createContext(ctx);
const run=s=>vm.runInContext(s,ctx);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
run(html.match(/function statNum[^\n]*/)[0]);
run(html.match(/const ANALYTIC_MARKETS=\{[\s\S]*?\n\};/)[0]);
run(html.match(/function pitchingOuts[^\n]*/)[0]);
run(html.match(/const PITCHER_ANALYTIC_MARKETS=\{[\s\S]*?\n\};/)[0]);
const source=fs.readFileSync(path.join(root,'research-upgrades.js'),'utf8');
run(source.slice(source.indexOf('function comparisonValue'),source.indexOf('function moreLessHtml')));
run(source.slice(source.indexOf('function isUpcomingResearchGame')));
run(fs.readFileSync(path.join(root,'research-tools.js'),'utf8'));
const future=new Date(Date.now()+3600000).toISOString();
ctx.pick={id:1,name:'Batter',team:'A',key:'hits',line:1,game:{gamePk:10,gameDate:future,status:{abstractGameState:'Preview'}},opponent:{name:'B'},score:.7};
ctx.finalGame={gamePk:10,status:{abstractGameState:'Final'}};
ctx.box={teams:{away:{players:{ID1:{battingOrder:'100',stats:{batting:{plateAppearances:4,hits:2}}}}},home:{players:{}}}};
run('captureResearchPicks([pick]);captureResearchPicks([pick])');
assert.equal(run('researchHistory.length'),1,'one frozen snapshot per game/player/market/line');
const captured=run('researchHistory[0].capturedAt');
ctx.pick.score=.9;run('captureResearchPicks([pick])');assert.equal(run('researchHistory[0].score'),.7);assert.equal(run('researchHistory[0].capturedAt'),captured);
ctx.pick.id=2;run('captureResearchPicks([pick])');assert.equal(run('researchHistory.length'),2,'replacement keeps original');
ctx.pick.id=3;ctx.pick.game.gameDate=new Date(Date.now()-1000).toISOString();run('captureResearchPicks([pick])');assert.equal(run('researchHistory.length'),2,'no retrospective capture');
assert.equal(run('researchOutcome(researchHistory[0],finalGame,box).status'),'win');
ctx.box.teams.away.players.ID1.stats.batting.hits=1;assert.equal(run('researchOutcome(researchHistory[0],finalGame,box).status'),'push');
ctx.box.teams.away.players.ID1.stats.batting.hits=0;assert.equal(run('researchOutcome(researchHistory[0],finalGame,box).status'),'loss');
delete ctx.box.teams.away.players.ID1.stats.batting.hits;assert.equal(run('researchOutcome(researchHistory[0],finalGame,box)'),null);
ctx.box.teams.away.players.ID1.battingOrder='101';assert.equal(run('researchOutcome(researchHistory[0],finalGame,box).status'),'void');
ctx.finalGame.status.abstractGameState='Live';assert.equal(run('researchOutcome(researchHistory[0],finalGame,box)'),null);
ctx.finalGame.status.detailedState='Postponed';assert.equal(run('researchOutcome(researchHistory[0],finalGame,box).status'),'void');
ctx.finalGame.status={abstractGameState:'Final'};
ctx.pitch={id:7,kind:'pitcher',market:'outs',line:17.5,direction:'more'};
ctx.box.teams.away.players.ID7={stats:{pitching:{gamesStarted:1,inningsPitched:'5.2'}}};
assert.equal(run('researchOutcome(pitch,finalGame,box).value'),17);
assert.equal(run('researchOutcome(pitch,finalGame,box).status'),'loss');
ctx.box.teams.away.players.ID7.stats.pitching.gamesStarted=0;assert.equal(run('researchOutcome(pitch,finalGame,box).status'),'void');
run("researchFresh('nfl',Date.now()-7200000)");assert(run("freshnessText('nfl','NFL',60)").includes('STALE'));
const stamp=run("researchHealth.get('nfl').at");run("researchFailed('nfl')");assert.equal(run("researchHealth.get('nfl').at"),stamp);assert(run("freshnessText('nfl','NFL',60)").includes('refresh failed'));
run("researchFresh('odds','invalid')");assert(run("freshnessText('odds','Odds',60)").includes('unavailable'));
run("toggleFavoritePlayer('MLB');toggleFavoritePlayer('NFL')");assert.equal(run('favoritePlayers.length'),2);assert.notEqual(run('favoriteKey(favoritePlayers[0])'),run('favoriteKey(favoritePlayers[1])'));
blocked=true;run('removeFavoritePlayer(0)');assert.equal(run('favoritePlayers.length'),2);assert.equal(run('storageProblem'),true);blocked=false;
assert.equal(JSON.parse(memory.get('ralloFavoritePlayersV1')).length,2);
run('removeFavoritePlayer(0)');assert.equal(run('favoritePlayers[0].sport'),'NFL');
ctx.state.memberActive=false;ctx.pick.game.gameDate=future;run('captureResearchPicks([pick])');assert.equal(run('researchHistory.length'),2);
console.log('PASS: pregame-only immutable captures, replacement history, wins/losses/pushes/voids, missing results, pitcher outs, stale timestamps, failed refresh age, separate MLB/NFL favorites, storage failure, membership capture guard');
